name: Export Docker Image

on:
  workflow_dispatch:

jobs:
  export-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Pull Docker Image
        run: |
          sudo docker pull nginx:latest

      - name: Save Docker Image to File
        run: |
          sudo docker save nginx:latest -o nginx.tar

      - name: Upload Image File
        uses: actions/upload-artifact@v3
        with:
          name: nginx-image
          path: nginx.tar

