name: Export Docker Image

on:
  workflow_dispatch:

jobs:
  export-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # 改成 v1

      - name: Pull Docker image
        run: docker pull alpine:latest

      - name: Save image to tar
        run: docker save alpine:latest -o alpine.tar

      - name: Upload tar as artifact
        uses: actions/upload-artifact@v2  # 改成 v2
        with:
          name: alpine-image
          path: alpine.tar
