name: Export Docker Image

on:
  workflow_dispatch:

jobs:
  export-image:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          docker --version

      - name: Pull Docker image
        run: docker pull alpine:latest

      - name: Save image to tar
        run: docker save alpine:latest -o alpine.tar

      - name: Upload image
        run: |
          echo "::group::Upload artifact"
          mkdir upload
          mv alpine.tar upload/
          zip -r alpine.zip upload
          echo "::endgroup::"
        shell: bash

      - name: Upload to GitHub Artifact
        uses: actions/upload-artifact@v3
        with:
          name: alpine-image
          path: alpine.tar
