name: Export Docker Image

on:
  workflow_dispatch:

jobs:
  export-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Pull Docker image
        run: |
          docker pull nginx:latest

      - name: Save image to tar
        run: |
          docker save nginx:latest -o ./nginx.tar

      - name: Upload tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: nginx-image
          path: ./nginx.tar
