name: Export Docker Image

on:
  workflow_dispatch:

jobs:
  export-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0a724b5e6fa6f40bc5a08b66b655f4a9f01c7a48

      - name: Pull Docker image
        run: docker pull alpine:latest

      - name: Save image to tar
        run: docker save alpine:latest -o alpine.tar

      - name: Upload artifact
        uses: actions/upload-artifact@1799279b66bafba4d60af26ef6dd1fc64aa5f32c
        with:
          name: alpine-image
          path: alpine.tar
